202151013_Akash_Maurya
iiitv/github-workshop-jan-2022 pull request #20
Opened 2022-01-30 07:10 UTC by akashma2209

update data.jason

2022-02-04 03:52 UTC, nlok5923 requested changes

2022-02-04 03:52 UTC, nlok5923 commented on ..txt
> +      "name": {Akash Maurua},
remove this file.

2022-02-04 03:52 UTC, nlok5923 commented on data.json
> +      "batch": {YOUR_BATCH_COMMENCEMENT_YEAR},
Please learn about `JSON` format. you can refer [this](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/JSON)

2022-02-04 05:06 UTC, akashma2209 commented
Update data.json

2022-02-05 13:58 UTC, nlok5923 commented
The changes done by you aren't correct PTAL.

2022-02-05 14:36 UTC, akashma2209 commented
update data.json

2022-02-05 14:37 UTC, akashma2209 commented
update data.json

2022-02-06 08:16 UTC, nlok5923 commented
Please remove the unnecessary `..txt` file and please format the code properly in `data.json`

2022-02-10 18:42 UTC, akashma2209 commented
Update data.json

2022-02-11 10:51 UTC, nlok5923 requested changes
Please address all the suggestions.

2022-02-11 10:51 UTC, nlok5923 commented on data.json
> +
```suggestion
```

2022-02-11 10:51 UTC, nlok5923 commented on data.json
> +        {
```suggestion
   {
```

2022-02-11 10:51 UTC, nlok5923 commented on data.json
> -{
Also please don't delete the existing code.

2022-02-11 12:11 UTC, akashma2209 commented
update data.json

2022-02-11 12:48 UTC, nlok5923 requested changes

2022-02-11 12:48 UTC, nlok5923 commented on data.json
>      }
```suggestion
    },
```

2022-02-11 12:50 UTC, merged